export const filterPokedexGameGroup = (index:number):number => {
    switch (index) {
        case 1:
        case 2:
            return 1
        case 3:
            return 2
        case 4: 
        case 5:
            return 3
        case 6:
            return 4
        case 7: 
        case 8:
            return 5
        case 9:
            return 6
        case 10:
        case 11:
            return 7
        case 12:
        case 13:
            return 8
        case 14:
            return 9
        case 15:
        case 16:
            return 10
        case 17:
        case 18:
            return 11
        case 19:
            return 12
        case 20:
            return 13
        case 21:
        case 22:
            return 14
        case 23:
        case 24:
            return 15
        case 25:
        case 26:
            return 16
        case 27:
        case 28:
            return 17
        case 29: 
        case 30:
            return 18
    }
}